### ISSUE TITLE
perl 6.0.0 fails to converge on windows

### ISSUE THREAD

**Issue by stefanwb** [sous-chefs/perl#34]
### Cookbook version
6.0.0

### Chef-client version
13.6

### Platform Details
Windows 2012R2

### Scenario:
Converging this CB

### Steps to Reproduce:
kitchen converge windows-server-2012

### Expected Result:
Successful converge

### Actual Result:
`
       Recipe: perl_test::default
         * perl_cpan_module[Install test module] action install
           * execute[CPAN :install Test::MockModule] action run

             ================================================================================
             Error executing action `run` on resource 'execute[CPAN :install Test::MockModule]'
             ================================================================================

             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0], but received '1'
             ---- Begin output of C:\strawberry\perl\bin\cpanm --quiet --notest Test::MockModule~">= 0.05" ----
             STDOUT: You do not have Perl in your PATH.
             STDERR: 'perl' is not recognized as an internal or external command,

             operable program or batch file.
             ---- End output of C:\strawberry\perl\bin\cpanm --quiet --notest Test::MockModule~">= 0.05" ----
             Ran C:\strawberry\perl\bin\cpanm --quiet --notest Test::MockModule~">= 0.05" returned 1

             Resource Declaration:
             ---------------------
             # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/perl/resources/cpan_module.rb

       10:   execute "CPAN :install #{new_resource.module_name}" do
       11:     cwd current_working_dir
       12:     command cpanm_install_cmd
       13:     environment 'HOME' => current_working_dir, 'PATH' => '/usr/local/bin:/usr/bin:/bin'
       14:     not_if { module_exists_new_enough }
       15:   end
       16: end

             Compiled Resource:
             ------------------
             # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/perl/resources/cpan_module.rb:10:in `block in class_from_file'

             execute("CPAN :install Test::MockModule") do
        action [:run]
        default_guard_interpreter :execute
        command "C:\\strawberry\\perl\\bin\\cpanm --quiet --notest Test::MockModule~\">= 0.05\""
        backup 5
        cwd "C:\\"
        environment {"HOME"=>"C:\\", "PATH"=>"/usr/local/bin:/usr/bin:/bin"}
        returns 0
        user nil
        declared_type :execute
        cookbook_name "perl_test"
        domain nil
        not_if { #code block }
             end

             System Info:
             ------------
             chef_version=13.6.4
             platform=windows
             platform_version=6.3.9600
             ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
             program_name=C:/opscode/chef/bin/chef-client
             executable=C:/opscode/chef/bin/chef-client

           ================================================================================
           Error executing action `install` on resource 'perl_cpan_module[Install test module]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           execute[CPAN :install Test::MockModule] (C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/perl/resources/cpan_module.rb line 10) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
           ---- Begin output of C:\strawberry\perl\bin\cpanm --quiet --notest Test::MockModule~">= 0.05" ----
           STDOUT: You do not have Perl in your PATH.
           STDERR: 'perl' is not recognized as an internal or external command,

           operable program or batch file.
           ---- End output of C:\strawberry\perl\bin\cpanm --quiet --notest Test::MockModule~">= 0.05" ----
           Ran C:\strawberry\perl\bin\cpanm --quiet --notest Test::MockModule~">= 0.05" returned 1

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/perl_test/recipes/default.rb

            11: cpan_module 'Install test module' do
            12:   module_name 'Test::MockModule'
            13:   version '>= 0.05'
            14:   action :install
            15: end
            16:

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/perl_test/recipes/default.rb:11:in `from_file'

           perl_cpan_module("Install test module") do
             action [:install]
             default_guard_interpreter :default
             declared_type :cpan_module
             cookbook_name "perl_test"
             recipe_name "default"
             module_name "Test::MockModule"
             version ">= 0.05"
           end

           System Info:
           ------------
           chef_version=13.6.4
           platform=windows
           platform_version=6.3.9600
           ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
           program_name=C:/opscode/chef/bin/chef-client
           executable=C:/opscode/chef/bin/chef-client

       Running handlers:
       [2017-12-21T05:45:03-08:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-12-21T05:45:03-08:00] ERROR: Exception handlers complete
       Chef Client failed. 4 resources updated in 02 minutes 09 seconds
       [2017-12-21T05:45:03-08:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2017-12-21T05:45:03-08:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-12-21T05:45:03-08:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: perl_cpan_module[Install test module] (perl_test::default line 11) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[CPAN :install Test::MockModule] (C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/perl/resources/cpan_module.rb line 10) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of C:\strawberry\perl\bin\cpanm --quiet --notest Test::MockModule~">= 0.05" ----
       STDOUT: You do not have Perl in your PATH.
       STDERR: 'perl' is not recognized as an internal or external command,
       operable program or batch file.
       ---- End output of C:\strawberry\perl\bin\cpanm --quiet --notest Test::MockModule~">= 0.05" ----
       Ran C:\strawberry\perl\bin\cpanm --quiet --notest Test::MockModule~">= 0.05" returned 1
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-windows-server-2012r2-standard>.  Please see .kitchen/logs/default-windows-server-2012r2-standard.log for more details`

**Comment by stefanwb** [comment]
Chef 13 is EOL
